target-version = "py310"

lint.extend-select = [
    "F",
    "E",
    "W",
    "C90",
    "I",
    "N",
    "D",
    "UP",
    "YTT",
    "ASYNC",
    "S",
    "BLE",
    "FBT",
    "B",
    "A",
    "COM",
    "C4",
    "T10",
    "EM",
    "EXE",
    "FA",
    "ISC",
    "ICN",
    "LOG",
    "G",
    "INP",
    "PIE",
    "PYI",
    "PT",
    "Q",
    "RSE",
    "RET",
    "SLF",
    "SLOT",
    "SIM",
    "TID",
    "TC",
    "ARG",
    "PTH",
    "TD",
    "FIX",
    "PGH",
    "PL",
    "TRY",
    "FLY",
    "FAST",
    "PERF",
    "FURB",
    "RUF",
]

lint.ignore = [
    "DTZ",
    "E501",
    "D1",
    "FBT003",
    "D203",
    "D213",
    "D400",
    "D401",
    "D415",
    "S311",
    "PERF401",
    "RET504",
    "TRY003",
    "EM101",
    "TC002",
    "TC003",
    "COM812",
    "ISC001",
]

[lint.per-file-ignores]
"tests/**" = ["ALL"]
"tests/*" = ["ALL"]